export const ORDER_STATUSES = [
  'IN_PROGRESS',
  'SHIPPED',
  'IN_BACKORDER',
  'MANCO',
  'CANCELED',
  'IN_COMBI',
  'CLOSED',
  'NEW',
  'RETURNED',
  'REQUIRES_CORRECTION',
  'AWAITING_PAYMENT',
]
